### ISSUE TITLE
Missing file in repository

### ISSUE THREAD

**Issue by jabruniessner** [SergeDmi/ConfocalGN#1]
Dear Dr Dmitrieff,

I am sorry to disturb you.

in the search of a good tool for generating realistic confocal images, I stumbled across yours and Dr. Nedelecs program ConfocalGN. I managed to get to run the example, however in the paper it says that the example runs setting the parameter

conf.psf = "gauss_psf .tiff ",

but in the example file cgn_example.m on github the paramter is set to

conf.psf=[13 13 22];

Moreover, I could not find the file gauss_psf.tiff on the github repository. I am curious for the file because I would like to use it after generating a PSF function in form of a tifffile. I used the FIji plugin  PSF Generator, which returns a stack of images instead if a single 2D image. Does the program also work with that?

Thank you for your time and best regards

Jakob Niessner

**Comment by SergeDmi** [comment]
Dear Jakob,

Thanks for your interest in cGN :) 

The file is actually in the repo : https://github.com/SergeDmi/ConfocalGN/blob/master/gauss_psf.tiff
In the default example, the psf is a 3D gaussian of variance 13.0, 13.0, 22.0 -- but a filename for a 3D image can be provided as well. gauss_psf.tiff is thus a 3D stack. 

As far as I know, PSF from PSF generator should directly work - but tiff images can be tricky sometimes so I would recomend to do a unit test before (e.g. convolve it with a very simple ground truth image such as a single dot).

Cf confocal_generator.m : https://github.com/SergeDmi/ConfocalGN/blob/master/cgn/confocal_generator.m
% * conf.psf is the point spread function of the microscope 
%       it is the 2-way psf (i.e. illumination+observation)
%       also called confocal psf  
%   It can be :
%       - Either a 1x3 vector
%   this assumes the psf to be gaussian (which provides fast convolution)
%   the PSF is in units of the size of original image pixel 
%   ex : psf = [wx,wy,wz] where wi is the gaussian spread on axis i
%       - or an image to be convolved to the ground truth image
%   In this case, make sure the grount truth image and the PSF image have
%   pixels of the same physical size

**Comment by jabruniessner** [comment]
Oh, I found the file. It appears that there are to repos, One from Elsevier Software X and this one. On ScienceDirect they are both referenced at different places. That is a little bit confusing. Thanks!

I will close this issue for now

**Comment by SergeDmi** [comment]
Thanks for letting me know, don't hesitate if you have questions.
